### ISSUE TITLE
Installing AR Models

### ISSUE THREAD

**Issue by YevZl** [ridvanaltun/react-native-deepar#13]
Hi @ridvanaltun !
I've tried the example app and it works great, thank you.
Now I want to use react-native-deepar in my App, but I have some problems.
My react-native.config.js looks like this:
![example](https://user-images.githubusercontent.com/109987440/180856303-5bb60df1-a17e-410b-b54b-8bff4d9444e9.png)
Assets is used for custom fonts and I don't understand how to add AR models.

Can you explain me what to do in such case?

**Comment by ridvanaltun** [comment]
Hey @YevZl !

I believe you can set yout `react-native.config.js` like below:

```js
module.exports = {
  project: {
    ios: {},
    android: {}
  },
  assets: ['./src/assets/fonts', './src/assets/effects'],
};
```

Cheers!
