### ISSUE TITLE
 Error: Function components cannot have string refs. We recommend using useRef() instead. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-string-ref

### ISSUE THREAD

**Issue by geniushkg** [ridvanaltun/react-native-deepar#14]
I just followed steps mentioned in Readme file but cant move forward from here

 return (
        <SafeAreaView style={styles.container}>
            <Text>Camera Homescreen</Text>
            <DeepAR
                ref={deepARRef}
                apiKey="0c0bf879c6b93878a416410b57eebf11b2b8e43*********************60b3eb716*********"
                style={{ flex: 1 }}
                onInitialized={() => {
                    // ..
                }}
            />

        </SafeAreaView>
    );
    
    I am not able to get deepar view work ,whenever i add this to return funtion of react native component always throw error like function components cannot have string refs

**Comment by ridvanaltun** [comment]
Hi @geniushkg, Can you show me the whole code?

**Comment by geniushkg** [comment]
Hi Resolved it by removing typescript refrence , 

for Vanilla JS  *********
    const DeepARRef = useRef(null);

this works and string ref error is also removed , I think it was occuring due to 
this line -> 
  const deepARRef = useRef<IDeepARHandle>(null);

But I am not using typescript .
