### ISSUE TITLE
[Android] - Can't start recording a video

### ISSUE THREAD

**Issue by adembacajmemmo** [ridvanaltun/react-native-deepar#15]
Hi all, just tried this beautiful library, but seems that it won't start recording. 

I was trying 0.10.2 and just updated with 0.10.3 but it still won't start recording.

This is the error: 

`onError => Video recording resolution is 720 x 1460 type => 1`

`onError => Could not record video! Stack trace: [libcore.io.IoBridge.open(IoBridge.java:574), java.io.RandomAccessFile.<init>(RandomAccessFile.java:289), java.io.RandomAccessFile.<init>(RandomAccessFile.java:152), android.media.MediaMuxer.<init>(MediaMuxer.java:357), ai.deepar.ar.MediaMuxerWrapper.<init>(MediaMuxerWrapper.java:60), ai.deepar.ar.DeepAR.startVideoRecording(DeepAR.java:1489), com.reactnativedeepar.RNTDeepAR.startRecording(RNTDeepAR.java:334), com.reactnativedeepar.RNTDeepARViewManager.receiveCommand(RNTDeepARViewManager.java:189), com.reactnativedeepar.RNTDeepARViewManager.receiveCommand(RNTDeepARViewManager.java:24), com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:832), com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.executeWithExceptions(UIViewOperationQueue.java:323), com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:879), com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025), com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47), com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085), com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29), com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175), com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85), android.view.Choreographer$CallbackRecord.run(Choreographer.java:1140), android.view.Choreographer.doCallbacks(Choreographer.java:946), android.view.Choreographer.doFrame(Choreographer.java:870), android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127), android.os.Handler.handleCallback(Handler.java:938), android.os.Handler.dispatchMessage(Handler.java:99), android.os.Looper.loopOnce(Looper.java:210), android.os.Looper.loop(Looper.java:299), android.app.ActivityThread.main(ActivityThread.java:8105), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)] type => 3`

**Comment by ridvanaltun** [comment]
Hi @adembacajmemmo,

Sometimes the library gives error, but it starts recording anyway, can you try the example project in the repo? And can you share me your Android version you're currently using?

Thanks

**Comment by adembacajmemmo** [comment]
> Hi @adembacajmemmo,
> 
> Sometimes the library gives error, but it starts recording anyway, can you try the example project in the repo? And can you share me your Android version you're currently using?
> 
> Thanks
@ridvanaltun 
I am trying all the time, but it won't start. I am using: 

react-native: 0.65.2
android version: 12
device: Xiaomi Poco F3

**Comment by ridvanaltun** [comment]
> > Hi @adembacajmemmo,
> > Sometimes the library gives error, but it starts recording anyway, can you try the example project in the repo? And can you share me your Android version you're currently using?
> > Thanks
> > @ridvanaltun
> > I am trying all the time, but it won't start. I am using:
> 
> react-native: 0.65.2 android version: 12 device: Xiaomi Poco F3

Thanks, I will test the Android version in next week, If I found something let you know.

**Comment by adembacajmemmo** [comment]
@ridvanaltun Thank you, would be really good. If you need any help to debug it, we can jump on a call and check it together. We are looking for using DeepAR in a big project (currently it is used by some celebrities, like Luis Figo, Michael Owen and a lot of other world known celebrities)

**Comment by adembacajmemmo** [comment]
@ridvanaltun do we have any new? I coulnd't run it on Android yet

**Comment by ridvanaltun** [comment]
> @ridvanaltun do we have any new? I coulnd't run it on Android yet

Sorry for the delay, I was very busy so I couldn't check

**Comment by ridvanaltun** [comment]
@adembacajmem I investigate the issue, and I found below error, there is a permission issue:

```
insertFileIfNecessary failed
java.lang.IllegalArgumentException: Primary directory null not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
	at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:3369)
	at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:3021)
	at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:3779)
	at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:4363)
	at com.android.providers.media.MediaProvider.insert(MediaProvider.java:4063)
	at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:8364)
	at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:8459)

```

**Comment by adembacajmemmo** [comment]
Thank you very much @ridvanaltun . I will wait

**Comment by ridvanaltun** [comment]
> Thank you very much @ridvanaltun . I will wait

Can we make a meeting next week? You can reach my mail address from my profile, If you mail me I can share my calendar to set a proper meeting time
