### ISSUE TITLE
 AR Shoe

### ISSUE THREAD

**Issue by imranbs93** [ridvanaltun/react-native-deepar#17]
How can I use this feature? https://www.deepar.ai/use-cases/shoe-try-on

**Comment by ridvanaltun** [comment]
> How can I use this feature? https://www.deepar.ai/use-cases/shoe-try-on

Hi @imranbs93

Seems to me the AR Shoe feature only available for web SDK, but I'm not sure, so I asked this to DeepAR support. If I learn something new, I will leave a new comment here.

**Comment by ridvanaltun** [comment]
This feature is only available for web SDK for now 🤷‍♂️
