### ISSUE TITLE
Combining background segmenation with face masks in React Native.

### ISSUE THREAD

**Issue by Dhruv2110** [ridvanaltun/react-native-deepar#19]
Hi, can we combine background segmention with face masks?. Currently face masks are combining with overlap.

**Comment by MadCoderme** [comment]
You need to use different slots for them. For example, you can use **effect** slot for background segmentation and **mask** slot for face masks.

**Comment by Dhruv2110** [comment]
Not working. Also tried with changeParameterTexture and switchEffect. Only background segmentation is working.

**Comment by Dhruv2110** [comment]
Got the solution. Issue was with the AR models.

**Comment by MadCoderme** [comment]
What type of problem was it? Can you please explain?
