### ISSUE TITLE
OpenGL ES RGBA scaling shader creation unsuccessful

### ISSUE THREAD

**Issue by MadCoderme** [ridvanaltun/react-native-deepar#20]
Hi!

The library was working fine till day before yesterday. Suddenly, from yesterday, no more face related mask or effect works. However filters and effects where face detection and processing is not needed, works perfectly. 

At the same time, I am getting this error message right when deepar is initialized. 

`OpenGL ES RGBA scaling shader creation unsuccessful`

I am using the latest version, `10.5`

**Comment by awaisrana12** [comment]
I am getting the same issue

**Comment by ridvanaltun** [comment]
Hi guys!

I'm so sorry for this late answer,

Can you guys try latest version 0.11.0? This error should have been fixed in the latest version.

@MadCoderme @awaisrana12
