### ISSUE TITLE
Android build failed - "Execution failed for task ':react-native-deepar:bundleReleaseLocalLintAar'."

### ISSUE THREAD

**Issue by Dhruv2110** [ridvanaltun/react-native-deepar#23]
-Execution failed for task ':react-native-deepar:bundleReleaseLocalLintAar'.
-Error while evaluating property 'hasLocalAarDeps' of task ':react-native-deepar:bundleReleaseLocalLintAar'

-Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-deepar project caused this error: {projectDir}\node_modules\react-native-deepar\android\libs\deepar-3.4.4.aar

react-native : 0.68.2.
react-native-deepar : ^0.10.5

**Comment by ridvanaltun** [comment]
Seems to me, the issue is related to #1 and #16.

Can you show me a reproducible example? An example project, maybe?

**Comment by Dhruv2110** [comment]
Hi @ridvanaltun thanks for checking. Please check sample project [here](https://github.com/Dhruv2110/RN-deepar-example).
=> Enter API key in App.js.
=> npx react-native-asset.
=> cd android && gradlew assembleRelease.

**Comment by Dhruv2110** [comment]
> > Hi @ridvanaltun thanks for checking. Please check sample project [here](https://github.com/Dhruv2110/RN-deepar-example). => Enter API key in App.js. => npx react-native-asset. => cd android && gradlew assembleRelease.
> 
> Thanks for the example project,
> 
> `assembleRelease` not work somehow, but when I try `bundleRelease` command, there was no problem. I investigated the issue like for 2 hours with no luck. I suggest you use `./gradlew bundleRelease` command to generate release build until the issue resolve.

Can you please try any of the following solutions.
1.) https://stackoverflow.com/questions/60878599/error-building-android-library-direct-local-aar-file-dependencies-are-not-supp
2.) https://github.com/brim-borium/spotify_sdk/issues/99#issuecomment-878910598

Thanks

**Comment by Dhruv2110** [comment]
Found the solution. Instead of `./gradlew assembleRelease` try `./gradlew app:assembleRelease`. Now APK build is working fine even with `./gradlew assembleRelease`.

**Comment by AchrafBn** [comment]
I have the same issue , it does not work with  `./gradlew app:assembleRelease`

**Comment by Dhruv2110** [comment]
what is the error?

**Comment by AchrafBn** [comment]
<img width="1060" alt="Screenshot 2023-04-10 at 09 08 34" src="https://user-images.githubusercontent.com/11798130/230871274-722461be-c277-4428-9abb-ac1c1cca6a98.png">

**Comment by Dhruv2110** [comment]
I think expo is not supported. https://github.com/ridvanaltun/react-native-deepar/issues/5#issuecomment-1192980673
